name: flutter_bloc_auth
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  bloc: ^8.1.0
  dio: ^5.5.0+1
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  flutter_secure_storage: ^9.2.2
  formz: ^0.6.0
  get_it: ^7.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
